[2023-11-29 15:18:10,428] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_district_daily scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29 15:18:10,442] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_district_daily scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29 15:18:10,443] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:18:10,443] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2023-11-29 15:18:10,444] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:18:10,462] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_district_daily> on 2023-11-28 00:00:00+00:00
[2023-11-29 15:18:10,494] {standard_task_runner.py:52} INFO - Started process 5676 to run task
[2023-11-29 15:18:10,497] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_district_daily', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmptu49s8_y', '--error-file', '/tmp/tmpnjzkfdio']
[2023-11-29 15:18:10,498] {standard_task_runner.py:80} INFO - Job 99: Subtask insert_district_daily
[2023-11-29 15:18:10,563] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_district_daily scheduled__2023-11-28T00:00:00+00:00 [running]> on host 92ab6769debf
[2023-11-29 15:18:10,662] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-28T00:00:00+00:00
[2023-11-29 15:18:10,817] {logging_mixin.py:115} INFO - Error: relation "dim_case" does not exist
LINE 1: SELECT id, status FROM dim_case
                               ^
[2023-11-29 15:18:10,818] {python.py:173} INFO - Done. Returned value was: None
[2023-11-29 15:18:10,831] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=d_1_etl_FinalProject, task_id=insert_district_daily, execution_date=20231128T000000, start_date=20231129T151810, end_date=20231129T151810
[2023-11-29 15:18:10,871] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-29 15:18:10,912] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
