[2023-11-29 14:29:03,539] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29 14:29:03,550] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29 14:29:03,550] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 14:29:03,551] {taskinstance.py:1357} INFO - Starting attempt 8 of 8
[2023-11-29 14:29:03,552] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 14:29:03,570] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-28 00:00:00+00:00
[2023-11-29 14:29:03,581] {standard_task_runner.py:52} INFO - Started process 4624 to run task
[2023-11-29 14:29:03,586] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_province_daily', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmpz36nk2oe', '--error-file', '/tmp/tmpj7dl8u7r']
[2023-11-29 14:29:03,587] {standard_task_runner.py:80} INFO - Job 98: Subtask insert_province_daily
[2023-11-29 14:29:03,697] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_province_daily scheduled__2023-11-28T00:00:00+00:00 [running]> on host 92ab6769debf
[2023-11-29 14:29:03,793] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-28T00:00:00+00:00
[2023-11-29 14:29:03,965] {logging_mixin.py:115} INFO - Error: relation "dim_case" does not exist
LINE 1: SELECT id, status FROM dim_case
                               ^
[2023-11-29 14:29:03,966] {python.py:173} INFO - Done. Returned value was: None
[2023-11-29 14:29:03,979] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=d_1_etl_FinalProject, task_id=insert_province_daily, execution_date=20231128T000000, start_date=20231129T142903, end_date=20231129T142903
[2023-11-29 14:29:04,005] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-29 14:29:04,036] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
