[2023-11-29 15:18:32,548] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:18:32,558] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [queued]>
[2023-11-29 15:18:32,559] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:18:32,559] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-11-29 15:18:32,560] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-29 15:18:32,592] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-29 15:18:25.802002+00:00
[2023-11-29 15:18:32,599] {standard_task_runner.py:52} INFO - Started process 5698 to run task
[2023-11-29 15:18:32,606] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_1_etl_FinalProject', 'insert_province_daily', 'manual__2023-11-29T15:18:25.802002+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/d_1_etl_FinalProject.py', '--cfg-path', '/tmp/tmpa6xj2w10', '--error-file', '/tmp/tmpnj_ewr02']
[2023-11-29 15:18:32,607] {standard_task_runner.py:80} INFO - Job 102: Subtask insert_province_daily
[2023-11-29 15:18:32,672] {task_command.py:369} INFO - Running <TaskInstance: d_1_etl_FinalProject.insert_province_daily manual__2023-11-29T15:18:25.802002+00:00 [running]> on host 92ab6769debf
[2023-11-29 15:18:32,751] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_1_etl_FinalProject
AIRFLOW_CTX_TASK_ID=insert_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T15:18:25.802002+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-29T15:18:25.802002+00:00
[2023-11-29 15:18:32,794] {logging_mixin.py:115} INFO - Error: relation "dim_case" does not exist
LINE 1: SELECT id, status FROM dim_case
                               ^
[2023-11-29 15:18:32,795] {python.py:173} INFO - Done. Returned value was: None
[2023-11-29 15:18:32,808] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=d_1_etl_FinalProject, task_id=insert_province_daily, execution_date=20231129T151825, start_date=20231129T151832, end_date=20231129T151832
[2023-11-29 15:18:32,861] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-29 15:18:32,896] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
